"""Generate the bundled trigram table from local Gutenberg text files.

Usage: python3 tools/train_english.py /path/to/1342.txt /path/to/84.txt
No network access or Python dependency is needed to build/run the application.
"""
import collections
import hashlib
import math
from pathlib import Path
import re
import sys

counts = collections.Counter()
sources = []
for name in sys.argv[1:]:
    raw = Path(name).read_bytes()
    text = raw.decode("utf-8-sig")
    text = re.split(r"\*\*\* START OF .*?\*\*\*", text, maxsplit=1)[1]
    text = re.split(r"\*\*\* END OF .*?\*\*\*", text, maxsplit=1)[0]
    text = re.sub("[^A-Z]", "", text.upper())
    counts.update(text[i:i + 3] for i in range(len(text) - 2))
    sources.append(f"{Path(name).name}: sha256 {hashlib.sha256(raw).hexdigest()}")
if not sources:
    raise SystemExit("Supply local corpus files.")
total = sum(counts.values()) + 0.1 * 26 ** 3
values = []
for a in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
    for b in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
        for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
            values.append(round(1000 * math.log((counts[a + b + c] + 0.1) / total)))
output = "/* Generated by tools/train_english.py. See docs/language-model.md.\n"
output += "\n".join(" * " + s for s in sources) + "\n */\n"
output += "static const int16_t english_trigrams[17576] = {\n"
output += "\n".join("    " + ", ".join(map(str, values[i:i + 12])) + ","
                    for i in range(0, len(values), 12))
output += "\n};\n"
Path("src/english_trigrams.inc").write_text(output)
